# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.2'

gem 'awesome_print'
gem 'rspec'
# gem 'byebug'
gem 'flay'
# gem 'mry'
gem 'pry-byebug'
gem 'reek'
gem 'rubocop'
gem 'rubocop-rspec'

gem 'sentry-ruby'
gem 'simplecov', require: false, group: :test
