# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'awesome_print'
gem 'debug'
gem 'rspec'
# gem 'byebug'
gem 'flay'
# gem 'mry'
# pronto hasn't been updated for over a year.
# gem 'pronto'
gem 'libyear-bundler'
gem 'pronto-flay'
gem 'pronto-standardrb'
gem 'reek'
gem 'rubocop'
gem 'rubocop-rspec'

gem 'sentry-ruby'
gem 'simplecov', require: false, group: :test

gem 'yard'

gem 'rubocop-performance'
