# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.2'

gem 'awesome_print'
gem 'debug'
gem 'rspec'
# gem 'byebug'
gem 'flay'
# gem 'mry'
gem 'pronto'
gem 'pronto-flay'
gem 'pronto-standardrb'
gem 'reek'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'standard'

gem 'sentry-ruby'
gem 'simplecov', require: false, group: :test

gem 'yard'
