#lang info
(define collection "bst")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
;(define build-deps '("scribble-lib" "racket-doc"))
(define scribblings '(("scribblings/bst.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(doolin))
(define license '(Apache-2.0 OR MIT))
