name: Elixir CI

on:
  push:
    # branches: [ master ]
  # pull_request:
  # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.11.1 # Define the elixir version [required]
          otp-version: 23.0.4 # Define the OTP version [required]

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get deps cache
        uses: actions/cache@v1
        with:
          path: deps/
          key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Get build cache
        uses: actions/cache@v1
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install Dependencies
        working-directory: ./elixir
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile

      - name: Security and Dependency Audit
        working-directory: ./elixir
        run: mix sobelow --config

      - name: Formatter
        working-directory: ./elixir
        run: mix format --check-formatted

      - name: Run Linter
        working-directory: ./elixir
        run: mix credo

      - name: Run Tests
        working-directory: ./elixir
        run: mix coveralls
